service: serverlessauth

frameworkVersion: '3'
plugins:
       - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  region: ap-south-1
functions:
  hello:
    handler: src/handlers/handler.user
    event:
      - http: 
         path: /getInfo
         method: get
