STAGE: local
CLOUD_REGION: ap-south-1
LAMBDA_VERSIONING_COUNT: 3
MAXIMUM_MEMORY: 256
MONGO_URL: mongodb+srv://digvijaygaur:ydIdU7aXCwnWpglD@cluster0.guash.mongodb.net/users?authSource=admin&replicaSet=atlas-vsho68-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true